CREATE SEQUENCE TASKS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;


CREATE TABLE TASKS (
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    DUE_DATE DATE,
    COMPLETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_TASKS_COMPLETED ON TASKS(COMPLETED);

CREATE INDEX IDX_TASKS_CREATED_AT ON TASKS(CREATED_AT);

CREATE INDEX IDX_TASKS_DUE_DATE ON TASKS(DUE_DATE);

